databases:
  - name: futureos-postgres
    databaseName: futureos
    user: futureos
    plan: free
    region: oregon

services:
  - type: web
    name: futureos-ai
    runtime: docker
    dockerfilePath: ./ai-service/Dockerfile
    dockerContext: ./ai-service
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_MODEL
        value: llama-3.3-70b-versatile

  - type: web
    name: futureos-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d8rf4fsm0tmc73c44320-a/futureos
      - key: DB_USERNAME
        value: futureos
      - key: DB_PASSWORD
        value: ZpcOdE0orc4T34A7u58xICMx00t178FE
      - key: JWT_SECRET
        sync: false
      - key: AI_BASE_URL
        value: https://futureos-ai.onrender.com

  - type: web
    name: futureos-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    region: oregon
    envVars:
      - key: VITE_API_BASE
        value: https://futureos-backend.onrender.com/api